ClientMVC/Controllers/Components/NavbarViewComponent.cs
using ClientMVC.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace ClientMVC.Controllers.Components
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly ILogger<AccountController> _logger;
        private readonly AccountService _accountService;

        public NavbarViewComponent(ILogger<AccountController> logger, AccountService accountService)
        {
            _logger = logger;
            _accountService = accountService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = _accountService.GetCurrentUser();
         
            return await Task.FromResult(View(user));
        }


    }
}

ClientMVC/Views/Shared/_ActivityDetailedChat.cshtml
<div class="card">
    <div class="card-header bg-info text-white text-center">
        Chat about this event
    </div>

    <div class="card-body py-2">
        <div class="row">
            <div class="col-2">
                <img src="/images/user.png" class="rounded text-center" style="max-width:50px" alt="...">
            </div>
            <div class="col-10">
                <span class="font-size-h5 font-weight-bold">Matt</span> <small class="text-muted">Today at 5:42</small>
                <p>How fantastic</p>
                <small class="text-muted">reply</small>

            </div>
        </div>

        <div class="row">
            <div class="col-2">
                <img src="/images/user.png" class="rounded text-center" style="max-width:50px" alt="...">
            </div>
            <div class="col-10">
                <span class="font-size-h5 font-weight-bold">Matt</span> <small class="text-muted">Today at 5:42</small>
                <p>How fantastic</p>
                <small class="text-muted">reply</small>

            </div>
        </div>
        <br />
        <form>
            <textarea class="form-control" aria-label="With textarea"></textarea>
            <br />
            <button class=" btn btn-primary">
                <i class="fa fa-edit"></i>
                Add Reply
            </button>
        </form>
    </div>
</div>

ClientMVC/Views/Shared/_ActivityDetailedHeader.cshtml
@{
    var text = "Join Activity";
    var style = "btn btn-info";
    var action = "attend";

    if (Model.IsHost)
    {
        text = "Manage Event";
        style = "btn btn-warning text-white";
        action = "edit";
    }
    else
    {
        if (Model.IsGoing)
        {
            text = "Cancel Attendance";
            style = "btn btn-secondary";

        }
    }

}
<div class="card ">
    
    <div calss="@(Model.IsCancelled ? "box" : "") ">
        @if (Model.IsCancelled)
        {
            <div class="ribbon red"><span>Cancelled</span></div>
        }
        <img src="/images/categoryImages/@(Model.Category).jpg" class="card-img-top overlay-dark " alt="@Model.Category">

        <div class="card-img-overlay text-white d-flex align-items-center ">

            <div>
                <h3>@Model.Title</h3>
                <small>@Model.Date.ToShortDateString()</small>
                <p>Hosted by <a class="text-warning" asp-controller="Profiles" asp-action="index" asp-route-id="@Model.HostUsername">@Model.Host.DisplayName</a></p>

            </div>
        </div>
    </div>
</div>
<div class="card-footer bg-white d-flex justify-content-between ">
    <div>
        <a class="@style" asp-controller="activities" asp-action="@action" asp-route-id="@Model.Id">@text</a>
    </div>
    <div>
        @if (Model.IsHost)
        {
        <a class="@(Model.IsCancelled ? "btn btn-outline-success" : "btn btn-outline-danger")" asp-controller="activities" asp-action="attend" asp-route-id="@Model.Id">@(Model.IsCancelled ? "Re-activate Activity" : "Cancel Activity")</a>
        }
    </div>
</div>

ClientMVC/Views/Shared/_ActivityDetailedInfo.cshtml
<div class="card my-2">
    <div class="card-footer bg-white">
        <i class="fa fa-info mr-2 text-info"></i>@Model.Description
    </div>

    <div class="card-footer bg-white">
        <i class="fa fa-calendar mr-2 text-info"></i>@Model.Date.ToShortDateString()
    </div>
    <div class="card-footer bg-white">
        <i class="fa fa-map-marker mr-2 text-info"></i>@Model.Venue, @Model.City
    </div>   

</div>

ClientMVC/Views/Shared/_ActivityDetailedSidebar.cshtml
@model Activity
@if (Model != null)
{
    @if (Model.Attendees != null)
    {
        <div class="card">
            <div class="card-header bg-info text-white text-center">
                @Model.Attendees.Count @((Model.Attendees.Count == 1 ? "Person" : "People")) Going
            </div>
            @foreach (var attendee in Model.Attendees)
            {

                <div class="card-footer bg-white py-2 @(attendee.Username == Model.HostUsername ? "box" : "") ">
                    <div class="row">
                        @if (attendee.Username == Model.HostUsername)
                        {       
                            <div class="ribbon red"><span>Host</span></div>                         
                        }
                        <div class="col-3">
                            <a asp-controller="pofiles" asp-action="index" asp-route-id="@attendee.Username"><img src="@((attendee.Image != null) ? attendee.Image : "/images/user.png")" alt="" class="rounded-circle" style="max-width:60px;" /></a>

                        </div>
                        <div class="col-9">
                            <span class="font-size-h6 font-weight-bold text-primary">@attendee.DisplayName</span>

                            <br />
                            <small class="text-danger font-weight-bold">Following</small>

                        </div>
                    </div>
                </div>
                
            }

         </div>

    }

}

ClientMVC/Views/Shared/_ActivityFilters.cshtml
<div class="card">
    <div class="card-footer bg-white text-info font-weight-bold">
        <i class="fa fa-filter mr-2 text-info"></i>Filters
        
    </div>
</div>
<div class="card">

    <div class="card-footer bg-white">
        All Activities
    </div>

    <div class="card-footer bg-white">
        I'm going
    </div>
    <div class="card-footer bg-white">
        I'm hosting
    </div>

</div>

ClientMVC/Views/Shared/_ActivityList.cshtml
@model IEnumerable<IGrouping<string, Activity>>
@foreach (var group in Model)
{
    <small class="text-info font-weight-bolder">@group.Key</small>
    <div class="my-3">

        @foreach (var activity in group)
        {


            <div class="card mb-2">
                @if (activity.IsCancelled)
                {
                    <div class="bg-danger text-white text-center ">
                        <small>Cancelled</small>
                    </div>
                }
                <div class="card-body d-flex flex-column">

                    <div class="d-flex align-items-center">
                        <span class="mr-3">
                            <img src="~/images/user.png" class="rounded-circle" alt="" style="max-width:80px">
                        </span>
                        <div class="d-flex flex-column">
                            <span class="text-dark font-weight-bold font-size-h5">@activity.Title</span>
                            <small>hosted by @activity.Host?.DisplayName</small>
                            @if (activity.IsHost)
                            {
                                <small class="border border-danger border-3 text-danger bg-white px-2 pb-1 mt-2 font-weight-bold">You are hosting this activity</small>
                            }
                            @if (activity.IsGoing && !activity.IsHost)
                            {
                                <small class="border border-success border-3 text-success bg-white px-2 pb-1 mt-2 font-weight-bold">
                                    You are going to this activity
                                </small>
                            }
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-white d-flex align-items-center justify-content-between flex-wrap py-2">
                    <div class="py-1">
                        <i class="fa fa-clock mr-2"></i>@activity.Date.ToShortDateString()
                        <i class="fa fa-map-marker ml-3 mr-2"></i>@activity.Venue
                    </div>
                </div>
                <div class="card-footer py-1">
                    <small class="font-weight-normal"><partial name="_ActivityListItemAttendee" model="activity.Attendees" /></small>
                </div>
                <div class="card-footer  bg-white bg-whit py-4">

                    <div class="btn-toolbar justify-content-between" role="toolbar">
                        <small class="font-weight-bold">@activity.Description</small>
                        <div>
                            <a class="btn btn-danger" asp-controller="activities" asp-action="delete" asp-route-id="@activity.Id">Delete</a>
                            <a class="btn btn-info" asp-controller="activities" asp-action="details" asp-route-id="@activity.Id">View</a>

                        </div>
                    </div>
                </div>
                <!--end::Footer-->
            </div>

        }
    </div>

}

ClientMVC/Views/Shared/_ActivityListItemAttendee.cshtml
@model ICollection<Profile>
<div class="row">
        @if (Model != null)
        {

            @foreach (var attendee in Model)
            {
                <div class="col-2">

                    <partial name="_ProfileCard" model="@attendee" />

                    @*<a href="#" data-toggle="popover" title="@attendee.DisplayName" data-content="ss<image src='/images/user.png'/>@("<partial name='_ProfileCard' model='@attendee' />")">
                            <img src="@((attendee.Image!=null) ? attendee.Image : "/images/user.png")" alt="" class="rounded-circle" style="max-height:40px;" />
                        </a>*@

                </div>
            }

        }

</div>

ClientMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)

</head>
<body style=" background-color: #f3eded">
    <header>
        @await Component.InvokeAsync("Navbar")

    </header>
    <div class="container" style="margin-top:75px;">
        @RenderBody()

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery-3.5.1.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <partial name="_ValidationScriptsPartial" />

    @await Component.InvokeAsync("NToastNotify")

    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover();
        });
    </script>

</body>
</html>

ClientMVC/Views/Shared/_ProfileCard.cshtml
@model Profile
<div class="card mb-0 bp-0"  style="max-width:75px;">
    <div class="card-img-wrapper text-center">
        <img src="@(!String.IsNullOrEmpty(Model.Image)?Model.Image:"/images/user.png")" class="card-img-top"/>
    </div>
    <div class="card-body text-center p-0 m-0">
        <small>
            @Model.DisplayName
        </small>
    </div>
    <div class="card-footer p-0 m-0">
        <i class="fa fa-user"></i>
        <small class="text-muted">20 followers</small>
    </div>
</div>